<?php
/**
 * @file
 * Adds numbers
 */
 
/**
 * Implements hook_menu().
 *
 * Adds Summer link to main menu.
 */
function summer_menu() {
  $items['summer'] = array(
    'title' => 'Summer',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('summer_form'),
    'access callback' => TRUE,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM    
  );
  return $items;
}

/**
 * Implements hook_form().
 */
function summer_form($form, &$form_state) {
  $form['num1'] = array(
    '#type' => 'textfield',
    '#title' => 'Number 1 (Maximum ten digits.)',
    '#size' => 10,
    '#maxlength' => 10,
    '#required' => TRUE
  );
  
  $form['num2'] = array(
    '#type' => 'textfield',
    '#title' => 'Number 2 (Maximum ten digits.)',
    '#size' => 10,
    '#maxlength' => 10,
    '#required' => TRUE
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit!')
  );
  
  return $form;
}

function summer_form_validate($form, &$form_state) {
  if (!is_numeric($form_state['values']['num1'])){
    form_set_error('num1', t('Number 1 must be a number.'));
  }
  if (!is_numeric($form_state['values']['num2'])){
    form_set_error('num2', t('Number 2 must be a number.'));
  }
}

function summer_form_submit($form, &$form_state) {
  $sum = $form_state['values']['num1'] + $form_state['values']['num2']; 
  drupal_set_message($sum);
}